landing/urls.py
from django.conf.urls import patterns, include, url

from landing import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index')
)

mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('vandali.urls', namespace='vandali')),
)

vandali/urls.py
from django.conf.urls import patterns, url

from vandali import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^portfolio/$', views.portfolio, name='portfolio'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^blog/$', views.blog, name='blog'),
)

landing/models.py
from django.db import models

# Create your models here.

landing/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'landing/index.html')

vandali/views.py
from django.shortcuts import render, render_to_response, redirect

def index(request):
    return render(request, 'vandali/index.html')

def about(request):
    return render(request, 'vandali/about.html')

def portfolio(request):
    return render(request, 'vandali/portfolio.html')

def contact(request):
    return render(request, 'vandali/contact.html')

def blog(request):
    return render(request, 'vandali/blog.html')

landing/templates/landing/index.html
hello
hi there!

vandali/templates/vandali/about.html
{% extends "base.html" %}
{% block title %}
About me
{% endblock %}
{% autoescape on %}
{% block body %}
<div class="container">
{% block banner %}
    {% include "banner.html" %}    
{% endblock %}
{% block menu %}
    {% include "menu.html" %}    
{% endblock %}
{% block content %}
    <div class="row clearfix">
        <div class="col-md-12 column">
        About me.
        </div>
    </div>
{% endblock %}
</div>
{% endblock%}
{% endautoescape %}

vandali/templates/vandali/banner.html
<h1>HELLO</h1>

vandali/templates/vandali/base.html
{% autoescape off%}
<!DOCTYPE html>
<html>
<head>	
	{% include "common_head.html" %}
	{% block extra_head %}
	{% endblock %}
	<title>{% block title%} {% endblock %} | Vandali </title>
</head>
<body>
	{% block body %}
	{% block banner %}
	{% endblock %}
	{% block menu %}
	{% endblock %}
	{% block content %}
	{% endblock %}
	{% endblock %}
</body>
</html>	
{% endautoescape %}

vandali/templates/vandali/blog.html
{% extends "base.html" %}
{% block title %}
Blog
{% endblock %}
{% block body %}
{% block menu %}
	{% include "menu.html" %}
{% endblock%}
{% block content %}
	Blog
{% endblock %}
{% endblock%}

vandali/templates/vandali/common_head.html
{% load staticfiles %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="A personal website of Aldrin A. Navarro">
<meta name="author" content="Aldrin A. Navarro">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>

vandali/templates/vandali/contact.html
{% extends "base.html" %}
{% block title %}
Contact
{% endblock %}
{% autoescape on %}
{% block body %}
<div class="container">
{% block banner %}
    {% include "banner.html" %}    
{% endblock %}
{% block menu %}
    {% include "menu.html" %}    
{% endblock %}
{% block content %}
    <div class="row clearfix">
        <div class="col-md-12 column">
        Contact
        </div>
    </div>
{% endblock %}
</div>
{% endblock%}
{% endautoescape %}

vandali/templates/vandali/index.html
{% extends "base.html" %}
{% block title %}
Welcome to my web space!
{% endblock %}
{% autoescape on %}
{% block body %}
<div class="container">
{% block banner %}
    {% include "banner.html" %}    
{% endblock %}
{% block menu %}
    {% include "menu.html" %}
{% endblock %}
{% block content %}
    <div class="row clearfix">
        <div class="col-md-12 column">
        I am home
        </div>
    </div>
{% endblock%}
</div>
{% endblock%}
{% endautoescape %}

vandali/templates/vandali/menu.html
<div class="row clearfix">
	<div class="col-md-12 column">
		<nav class="navbar navbar-default navbar-static-top" role="navigation">		
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="{% url 'vandali:index' %}">Home</a></li>
					<li><a href="{% url 'vandali:about' %}">About</a></li>
					<li><a href="{% url 'vandali:portfolio' %}">Portfolio</a></li>
					<li><a href="{% url 'vandali:contact' %}">Contact</a></li>
				</ul>
			</div>
			
		</nav>
	</div>
</div>

vandali/templates/vandali/portfolio.html
{% extends "base.html" %}
{% block title %}
Portfolio
{% endblock %}
{% autoescape on %}
{% block body %}
<div class="container">
{% block banner %}
    {% include "banner.html" %}    
{% endblock %}
{% block menu %}
    {% include "menu.html" %}    
{% endblock %}
{% block content %}
    <div class="row clearfix">
        <div class="col-md-12 column">
        What I do?
        </div>
    </div>
{% endblock %}
</div>
{% endblock%}
{% endautoescape %}